import Head from 'next/head'
import Header from '../components/Header';

export default function Home() {
    return (
        <div>
            <Head>
                <title>
                    Social Nick
                </title>

                <meta name='description' content='Generated by create next app' />

                <link rel='icon' href='/facebook.png' />
            </Head>

            <Header />

        {/*BODY*/}
            <div>
            {/*SIDEBAR*/}
            {/*FEED*/}
            {/*CONTACTS*/}
            </div>
        </div>
    )
}
